const AuditSphere = `

<div class ="row">
<h2>Problem</h2>
    <p class = "tab">Biases generated by GenAI exist everywhere and currently, there aren’t any effective solutions. There’s also a high motivation barrier to report biases, compounded with a lack of awareness of existing biases and how to report them for everyday GenAI users. Our research aims to raise the public awareness of auditing GenAI biases and provide an effective way to motivate users to report biases.
</p>
</div>

<div class ="row">
<h2>Solution</h2>
    <p class = "tab">From our insights we created an application called AuditSphere. This is an application that allows users not only to report GenAI Biases but they can interact with other reporters, see their own personal impact in improving AI, and can see an interactive map of the whole world showing that they aren’t alone in making an impact. 
</p>
</div>

<div class ="row">
    <div class="col-lg-12 project_images">
    <img src = "../Images/AuditSphere/poster.png" alt = "Poster Submission for DEI Summer 2024">
    <p class = "project_caption">Poster Submission</p>
    </div>
</div>


<div class = "row">
<h2>Process</h2>
    <div class = "col-lg-12">
        <p class = "tab">Throughout the class me and my group used a thourough process of interviews as well as user centered design and analysis methods such as affinity diagraming
        , journey mapping, empathy mapping, crazy 8s, and storyboarding to get a strong understanding of our users, their needs, and any questions we have. We created all of our 
        artifacts into a wall to see themes and connections between our different methods. All of this led us to our final assumption artifiact to help us solve the problem of GenAI Bias.</p>

       
</div>
<div class ="row">

    <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Empathy.png" alt = "Empathy Map">
    <p class = "project_caption">Empathy Map</p>
    </div>

     <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Journey.png" alt = "Customer Journey Map">
    <p class = "project_caption">Customer Journey Map</p>
    </div>

</div>

<div class ="row">

    <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Crazy8.png" alt = "Crazy8s">
    <p class = "project_caption">Crazy 8s</p>
    </div>

     <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/StoryBoards.png" alt = "Storyboards">
    <p class = "project_caption">Storyboards</p>
    </div>
    
</div>

<div class ="row">
<h2>Reflection</h2>
   <div class = "col-lg-12">
        <p class = "tab"><p class = "tab">Our work on AuditSphere highlighted the complex challenge of addressing biases in Generative AI systems while balancing user motivation and awareness. This project was a journey of understanding not only the technical problem but also the human behaviors that influence meaningful change.</p>
        <p class = "tab"><p class = "tab">One of the biggest takeaways from our process was recognizing the importance of user-centered design in tackling societal and technological issues. Through methods like empathy mapping and journey mapping, we were able to identify pain points such as users feeling isolated, powerless, or unaware of how to act against AI bias. These insights guided us to design a solution that is interactive, empowering, and community-driven. By visualizing users' collective impact, we aimed to reduce motivation barriers and foster a sense of unity among reporters.</p>
        <p class = "tab"><p class = "tab">Furthermore, the iterative process of ideation—from Crazy 8s to storyboarding—demonstrated the value of creative exploration. It allowed us to experiment with multiple design ideas, refine assumptions, and arrive at a solution that aligns with user needs and behaviors. Building artifacts such as the affinity diagram wall helped us uncover connections between user data and solidify key themes, providing a robust foundation for our application.</p>
        <p class = "tab"><p class = "tab">Ultimately, the development of AuditSphere reinforced the importance of design thinking in solving real-world problems. By empowering users to report biases and fostering a global community, we hope to contribute to creating more equitable AI systems. This experience has taught us that technology alone cannot solve problems—thoughtful, human-centered design is essential to driving progress and building trust in the systems we create.</p>

    
</div>





`;

export { AuditSphere };
