const AuditSphere = `

<div class ="row">
<h2>Problem</h2>
    <p class = "tab">Biases generated by GenAI exist everywhere and currently, there aren’t any effective solutions. There’s also a high motivation barrier to report biases, compounded with a lack of awareness of existing biases and how to report them for everyday GenAI users. Our research aims to raise the public awareness of auditing GenAI biases and provide an effective way to motivate users to report biases.
</p>
</div>

<div class ="row">
<h2>Solution</h2>
    <p class = "tab">From our insights we created an application called AuditSphere. This is an application that allows users not only to report GenAI Biases but they can interact with other reporters, see their own personal impact in improving AI, and can see an interactive map of the whole world showing that they aren’t alone in making an impact. 
</p>
</div>

<div class ="row">
    <div class="col-lg-12 project_images">
    <img src = "../Images/AuditSphere/Poster.png" alt = "Poster Submission">
    <p class = "project_caption">Poster Submission</p>
    </div>
</div>


<div class = "row">
<h2>Process</h2>
    <div class = "col-lg-12">
        <p class = "tab">Throughout the class my group and I used a thourough process of interviews as well as user centered design and analysis methods such as affinity diagraming, journey mapping, empathy mapping, crazy 8s, and storyboarding to get a strong understanding of our users, their needs, and any questions we have. We created all of our 
        artifacts into a wall to see themes and connections between our different methods. All of this led us to our final assumption artifiact to help us solve the problem of GenAI Bias.</p>

       
</div>
<div class ="row">

    <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Empathy.png" alt = "Empathy Map">
    <p class = "project_caption">Empathy Map</p>
    </div>

     <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Journey.png" alt = "Customer Journey Map">
    <p class = "project_caption">Customer Journey Map</p>
    </div>

</div>

<div class ="row">

    <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/Crazy8.png" alt = "Crazy8s">
    <p class = "project_caption">Crazy 8s</p>
    </div>

     <div class="col-lg-6 project_images">
    <img src = "../Images/AuditSphere/StoryBoards.png" alt = "Storyboards">
    <p class = "project_caption">Storyboards</p>
    </div>
    
</div>

<div class ="row">
<h2>Reflection</h2>
   <div class = "col-lg-12">
        <p class="tab">Our work on AuditSphere aimed at addressing the biases embedded in Generative AI systems while navigating the complexities of user motivation and impact. This project had us consider not only the technical aspects of AI but also the human behaviors that drive meaningful change in the world.</p>

        <p class="tab"><strong>User-Centered Design as a Driving Force</strong></p>
        <p class="tab">One of the most valuable lessons from this project was the critical role of user-centered research in solving complex societal and technological issues. By employing tools like empathy mapping and journey mapping as well as numerous interviews among other user research methods we uncovered pain points such as users feeling unmotivated, powerless, or uncertain about how to combat AI bias. These insights informed our design approach, leading us to create an interactive, empowering, and community-driven solution. By visualizing users' collective impact, AuditSphere aimed to solve the motivation barriers and foster a sense of unity among reporters in hopes of encouraging participation.</p>

        <p class="tab"><strong>Driving Impact Through Thoughtful Design</strong></p>
        <p class="tab">The development of our AuditSphere prototype was a challenge in of itself. We were tying to figure out how to address all of our insights and customer pain points while driving progress and attempting to build trust in the systems we create. There was many factors to consider in our final design but overall I am happy with the map approach that we took.</p>

        <p class="tab"><strong>Reflection on My Role and Growth</strong></p>
        <p class="tab">My contributions to AuditSphere highlight my ability to blend research and design to create impactful solutions. From analyzing user data to synthesizing insights into actionable design elements, I have strengthened my skills in aligning technical possibilities with human needs. Revisiting my initial learning goals for the semester, I can confidently say that I have grown as a multidisciplinary UX contributor as well as gained skills I can bring into my more technically focused courses as an Information Systems Major. This project has refined my ability to collaborate, ideate, and advocate for users in complex systems—a skill set I aim to bring to future teams and challenges.</p>



    
</div>





`;

export { AuditSphere };
